spring.application.name=prompt-and-tools

spring.ai.chat.client.enabled=false
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

#Perplexity AI Configuration
spring.ai.openai.api-key=
spring.ai.openai.base-url=https://api.perplexity.ai
spring.ai.openai.chat.completions-path=/chat/completions
spring.ai.openai.chat.options.model=sonar
spring.ai.openai.chat.options.temperature=0.2

#Google Gemini Configuration
spring.ai.google.genai.api-key=
spring.ai.google.genai.chat.options.model=gemini-flash-latest

#H2 In memory DB Configuration
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:./.db/chatmemory;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=debmalya
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.chat.memory.repository.jdbc.schema=classpath:/schema/schema-h2db.sql


